//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loom.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loom.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: The aspect already defines an introduction method for interface method {1}..
        /// </summary>
        internal static string ERR_0001 {
            get {
                return ResourceManager.GetString("ERR_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid aspect parameter &apos;{0}&apos; in method &apos;{1}&apos;: An unspecified aspect parameter is not allowed..
        /// </summary>
        internal static string ERR_0002 {
            get {
                return ResourceManager.GetString("ERR_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: The target class &apos;{1}&apos; already defines the interface {2}. Try option &apos;{3}&apos; to resolve this..
        /// </summary>
        internal static string ERR_0003 {
            get {
                return ResourceManager.GetString("ERR_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid aspect parameter &apos;{0}&apos; in method &apos;{1}&apos;: &apos;{3}&apos; is not allowed in this context..
        /// </summary>
        internal static string ERR_0004 {
            get {
                return ResourceManager.GetString("ERR_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid aspect parameter &apos;{0}&apos; in method &apos;{1}&apos;: The expected type was &apos;{2}&apos;..
        /// </summary>
        internal static string ERR_0005 {
            get {
                return ResourceManager.GetString("ERR_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid aspect method &apos;{0}&apos;: There is more than one aspect-method attribute defined.
        /// </summary>
        internal static string ERR_0006 {
            get {
                return ResourceManager.GetString("ERR_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only interfaces can be introduced..
        /// </summary>
        internal static string ERR_0007 {
            get {
                return ResourceManager.GetString("ERR_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid aspect method &apos;{0}&apos;: initializers are expected to be &apos;void&apos;.
        /// </summary>
        internal static string ERR_0008 {
            get {
                return ResourceManager.GetString("ERR_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} introduces interface {1} but doesn&apos;t implement method {2}..
        /// </summary>
        internal static string ERR_0009 {
            get {
                return ResourceManager.GetString("ERR_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter declaration in method {0}.{1}: The aspect parameter {2} could occour only at the beginning of the parameter list..
        /// </summary>
        internal static string ERR_0010 {
            get {
                return ResourceManager.GetString("ERR_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aspect method &apos;{0}&apos; mustn&apos;t return a value: Aspect methods except some Advice.Around and Advice.AfterThrowing methods are expected to be &apos;void&apos;..
        /// </summary>
        internal static string ERR_0011 {
            get {
                return ResourceManager.GetString("ERR_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aspect method &apos;{0}&apos; mustn&apos;t return &apos;{1}&apos;: The return type of {2} methods (annotated with pointcut attributes) is expected to be a generic type..
        /// </summary>
        internal static string ERR_0012 {
            get {
                return ResourceManager.GetString("ERR_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave {0} with aspect {1}: The following aspect methods have undecidable pointcuts:\n{2}.
        /// </summary>
        internal static string ERR_0013 {
            get {
                return ResourceManager.GetString("ERR_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aspect-method &apos;{0}&apos; tries to introduce the private interface &apos;{1}&apos;. Introductions are only allowed for public interfaces..
        /// </summary>
        internal static string ERR_0014 {
            get {
                return ResourceManager.GetString("ERR_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter declaration in aspect method &apos;{0}&apos;: Aspect methods using the Destroy attribute are expected to be parameterless. Only Aspect parameter attributes are allowed..
        /// </summary>
        internal static string ERR_0015 {
            get {
                return ResourceManager.GetString("ERR_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong visiblity of join-point variable &apos;{0}&apos;: The visibility change in {1} to &apos;{2}&apos; is not allowed..
        /// </summary>
        internal static string ERR_0016 {
            get {
                return ResourceManager.GetString("ERR_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid use of the join-point variable scope &apos;Override&apos;: Cannot override non-existing target class member &apos;{0}&apos; using join-point variable &apos;{0}&apos; on aspect method {1}..
        /// </summary>
        internal static string ERR_0017 {
            get {
                return ResourceManager.GetString("ERR_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent visibility of the join-point variable &apos;{0}&apos;: The scope of &apos;{0}&apos; was defined different on multiple aspect methods. Error occured at {1}..
        /// </summary>
        internal static string ERR_0018 {
            get {
                return ResourceManager.GetString("ERR_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal combination of Scopes for join-point variable &apos;{0}&apos; at {1}..
        /// </summary>
        internal static string ERR_0019 {
            get {
                return ResourceManager.GetString("ERR_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of join-point variable &apos;{0}&apos; in &apos;{1}&apos;: The expected type was &apos;{2}&apos; and was declared in &apos;{3}&apos;..
        /// </summary>
        internal static string ERR_0020 {
            get {
                return ResourceManager.GetString("ERR_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter &apos;{0}&apos; in &apos;{1}&apos;: A local join-point variable is not allowed for [Create] Advices..
        /// </summary>
        internal static string ERR_0021 {
            get {
                return ResourceManager.GetString("ERR_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aspect method &apos;{0}&apos; has conflicting return type constraints. The declared return type and the aspect parameter type of [JPRetVal] have to be identical.  .
        /// </summary>
        internal static string ERR_0022 {
            get {
                return ResourceManager.GetString("ERR_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute is no longer supported. Go to the documentation for further information..
        /// </summary>
        internal static string ERR_0023 {
            get {
                return ResourceManager.GetString("ERR_0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect {0} has a invalid XML configuration: {1}..
        /// </summary>
        internal static string ERR_0024 {
            get {
                return ResourceManager.GetString("ERR_0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration: Unable to resolve type &apos;{0}&apos; in assembly &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_0025 {
            get {
                return ResourceManager.GetString("ERR_0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error..
        /// </summary>
        internal static string ERR_9000 {
            get {
                return ResourceManager.GetString("ERR_9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation..
        /// </summary>
        internal static string ERR_9001 {
            get {
                return ResourceManager.GetString("ERR_9001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overload of the method or constructor takes the following arguments: {0}.
        /// </summary>
        internal static string ERR_9002 {
            get {
                return ResourceManager.GetString("ERR_9002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t invoke target method: The parameter count doesn&apos;t match..
        /// </summary>
        internal static string ERR_9003 {
            get {
                return ResourceManager.GetString("ERR_9003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined [Error] on join point {0}: {1}.
        /// </summary>
        internal static string ERR_9010 {
            get {
                return ResourceManager.GetString("ERR_9010", resourceCulture);
            }
        }
    }
}
