//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loom.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeBuilderErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeBuilderErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loom.Resources.CodeBuilderErrors", typeof(CodeBuilderErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t instantiate &apos;{0}&apos;: The type must be a class..
        /// </summary>
        internal static string ERR_1001 {
            get {
                return ResourceManager.GetString("ERR_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos; to &apos;{1}&apos;: There is already a Advice.Around method defined..
        /// </summary>
        internal static string ERR_1002 {
            get {
                return ResourceManager.GetString("ERR_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t introduce &apos;{0}&apos; due to its visibility..
        /// </summary>
        internal static string ERR_1003 {
            get {
                return ResourceManager.GetString("ERR_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: There is already an introduction for &apos;{1}&apos; defined..
        /// </summary>
        internal static string ERR_1004 {
            get {
                return ResourceManager.GetString("ERR_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: There is no introduction defined for &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_1005 {
            get {
                return ResourceManager.GetString("ERR_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create an instance of the abstract class &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_1006 {
            get {
                return ResourceManager.GetString("ERR_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave sealed class &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_1007 {
            get {
                return ResourceManager.GetString("ERR_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: The generic parameter &apos;{1}&apos; is not assigned..
        /// </summary>
        internal static string ERR_1008 {
            get {
                return ResourceManager.GetString("ERR_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate join-point parameter &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_1009 {
            get {
                return ResourceManager.GetString("ERR_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: &apos;Advice.Initialize&apos; aspect methods mustn&apos;t bind generic parameters (&apos;{1}&apos;) coming from target method definitions (generic parameter &apos;{2}&apos; in &apos;{3}&apos;). Use parameter wildcards instead. .
        /// </summary>
        internal static string ERR_1010 {
            get {
                return ResourceManager.GetString("ERR_1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave private class &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_1011 {
            get {
                return ResourceManager.GetString("ERR_1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: Parameters of type &apos;{1}&apos; are invalid..
        /// </summary>
        internal static string ERR_1012 {
            get {
                return ResourceManager.GetString("ERR_1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: The aspect method is expected to be declared as &apos;static&apos;..
        /// </summary>
        internal static string ERR_1013 {
            get {
                return ResourceManager.GetString("ERR_1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: {1} aspects mustn&apos;t use use parameterized constructors..
        /// </summary>
        internal static string ERR_1014 {
            get {
                return ResourceManager.GetString("ERR_1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t interweave &apos;{0}&apos;: The aspect has no constructor that accepts {1} parameter(s) of type {2}..
        /// </summary>
        internal static string ERR_1015 {
            get {
                return ResourceManager.GetString("ERR_1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error..
        /// </summary>
        internal static string ERR_9000 {
            get {
                return ResourceManager.GetString("ERR_9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is incompatible to array {1}. .
        /// </summary>
        internal static string ERRMSG_IncompatibleTypes {
            get {
                return ResourceManager.GetString("ERRMSG_IncompatibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter has no type..
        /// </summary>
        internal static string ERRMSG_NoTypeParam {
            get {
                return ResourceManager.GetString("ERRMSG_NoTypeParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array parameters mustn&apos;t have a scalar value. Use &lt;element&gt; ... &lt;/element&gt; instead..
        /// </summary>
        internal static string ERRMSG_ParamValue {
            get {
                return ResourceManager.GetString("ERRMSG_ParamValue", resourceCulture);
            }
        }
    }
}
